/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package priseEnMain;

/**
 *
 * @author aminiscloux
 */
public class FenCheckBox extends javax.swing.JFrame {

    /**
     * Creates new form FenCheckBox
     */
    public FenCheckBox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Titre = new javax.swing.JLabel();
        jLab_Message = new javax.swing.JLabel();
        jCheckBox_The = new javax.swing.JCheckBox();
        jCheckBox_Cafe = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel_Titre.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel_Titre.setText("Tea or Coffee");

        jLab_Message.setBackground(new java.awt.Color(102, 255, 102));
        jLab_Message.setText("Votre choix");
        jLab_Message.setOpaque(true);

        jCheckBox_The.setText("Thé");
        jCheckBox_The.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_TheActionPerformed(evt);
            }
        });

        jCheckBox_Cafe.setText("Coffee");
        jCheckBox_Cafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_CafeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jLabel_Titre))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLab_Message)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jCheckBox_The)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(jCheckBox_Cafe)
                .addGap(117, 117, 117))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel_Titre)
                .addGap(37, 37, 37)
                .addComponent(jLab_Message)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_The)
                    .addComponent(jCheckBox_Cafe))
                .addContainerGap(154, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(476, 389));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox_TheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_TheActionPerformed
        // TODO add your handling code here:
        if (jCheckBox_The.isSelected() == true) {
            jLab_Message.setText("Vous avez choisi du thé.");
            jCheckBox_Cafe.setSelected(false) ;
        }
        if (jCheckBox_The.isSelected() == false) {
            jLab_Message.setText("");
        }
    }//GEN-LAST:event_jCheckBox_TheActionPerformed

    private void jCheckBox_CafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_CafeActionPerformed
        // TODO add your handling code here:
        if (jCheckBox_Cafe.isSelected() == true) {
            jLab_Message.setText("Vous avez choisi du café.");
            jCheckBox_The.setSelected(false) ;
        }
        if (jCheckBox_Cafe.isSelected() == false) {
            jLab_Message.setText("");
    }//GEN-LAST:event_jCheckBox_CafeActionPerformed
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenCheckBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenCheckBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenCheckBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenCheckBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenCheckBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox_Cafe;
    private javax.swing.JCheckBox jCheckBox_The;
    private javax.swing.JLabel jLab_Message;
    private javax.swing.JLabel jLabel_Titre;
    // End of variables declaration//GEN-END:variables
}
